version: '3.8'

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    command:
      [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_general_ci, --query-cache-size=0, --query-cache-type=0]
    healthcheck:
      test: "mysqladmin -uroot -ppassword ping"
      interval: 3s
      timeout: 1s
      retries: 10
    platform: linux/x86_64
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command:
      [redis-server, --requirepass password, --port 6379]
